edits + edr links
Brown-University-Library/usep-data pull request #248
Opened 2021-06-22 10:23 UTC by spapando

2021-06-23 00:13 UTC, sdigiulio requested changes
In need of a few small corrections but otherwise good; check the comments throughout.

2021-06-23 00:13 UTC, sdigiulio commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.968.xml
> +                           <abbr><supplied reason="lost" evidence="previouseditor">D</supplied></abbr><ex>is</ex>
The change of "undefined" to "lost" here isn't particularly important, especially as the stylesheets will handle them identically using our output style. Certain other projects are customized to add other material when you handle it this way.

2021-06-23 08:25 UTC, spapando commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.318.xml
> -<?xml version="1.0" encoding="UTF-8"?><?oxygen RNGSchema="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng" type="xml"?><TEI xmlns:xi="http://www.w3.org/2001/XInclude" xmlns="http://www.tei-c.
I should've said something; it's a duplicate of 1431, but using Tuck's entry number instead of the museum inventory number.

2021-06-23 08:36 UTC, spapando commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.2981.xml
> +                <lb n="4"/>Caesaris <expan>
Isn't it more of a title here?

2021-06-23 09:11 UTC, spapando commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.21412.xml
> +                  <objectDesc ana="#instrumentum.other">
none of the other categories seem applicable?

2021-06-23 15:25 UTC, sdigiulio commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.318.xml
> -<?xml version="1.0" encoding="UTF-8"?><?oxygen RNGSchema="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng" type="xml"?><TEI xmlns:xi="http://www.w3.org/2001/XInclude" xmlns="http://www.tei-c.
OK, no problem here then; I'll mark as resolved.

2021-06-23 15:26 UTC, sdigiulio commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.21412.xml
> +                  <objectDesc ana="#instrumentum.other">
I thought we had kept `#document`; if not, we can ask at our weekly meeting.

2021-06-23 15:27 UTC, sdigiulio commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.2981.xml
> +                <lb n="4"/>Caesaris <expan>
There was a discussion on the markup list about this exact question recently; I still tend to come down on the side of it becoming part of the imperial nomenclature, but I think it's an open question. We can bring it up at the meeting or treat it as a title and not worry about it.

2021-06-23 15:33 UTC, spapando commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.21412.xml
> +                  <objectDesc ana="#instrumentum.other">
Do you mean you think this should be classified as a document? Because I thought that's how I left it.

2021-06-23 16:02 UTC, sdigiulio commented on xml_inscriptions/transcribed/MI.AA.UM.KM.L.21412.xml
> +                  <objectDesc ana="#instrumentum.other">
Sorry, I'm realizing I looked at the wrong part of the file; yes, this is totally fine as it is, and you can disregard here.

2021-06-30 16:52 UTC, sdigiulio approved these changes

2021-06-30 16:53 UTC, merged